alias net="/usr/bin/bash \"${HOME}/.local/etc/rc/StartNetworking.sh\""
alias o="xdg-open"
alias icat="kitty +kitten icat"
alias reboot="systemctl reboot --boot-loader-entry=arch.conf"
alias reboot-windows="systemctl reboot --boot-loader-entry=windows.conf"
